# **Note:-**

pytorch.nn module is a core module in pytorch which provides multiple classes and functions to develop neural networks efficiently.

In [16]:
import torch
import torch.nn as nn

In [17]:
# Create Model Class

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [18]:
# Create Dataset
features = torch.rand(10,5)

# Create Model

model = Model(features.shape[1])

# Forward Pass
model(features) # We can also do this model.forward(features)

tensor([[0.3818],
        [0.3787],
        [0.3787],
        [0.3825],
        [0.3787],
        [0.3792],
        [0.3787],
        [0.3809],
        [0.3787],
        [0.3882]], grad_fn=<SigmoidBackward0>)

In [19]:
# Show Model Weights
model.linear1.weight

Parameter containing:
tensor([[ 0.0359, -0.4378, -0.0009,  0.2951,  0.2639],
        [-0.3601, -0.0041,  0.3319,  0.2202, -0.3387],
        [-0.2980,  0.2285,  0.0319, -0.3657, -0.2931]], requires_grad=True)

In [21]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1962, -0.2389, -0.2098]], requires_grad=True)

In [22]:
# Show Model Bias
model.linear1.bias

Parameter containing:
tensor([-0.1249, -0.1731, -0.1303], requires_grad=True)

In [23]:
model.linear2.bias

Parameter containing:
tensor([-0.4952], requires_grad=True)

In [14]:
# !pip install torchinfo

In [24]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00