# **Note:-**

pytorch.nn module is a core module in pytorch which provides multiple classes and functions to develop neural networks efficiently.

In [2]:
import torch
import torch.nn as nn

In [9]:
# Create Model Class

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)  # Here we are calculating the z
    out = self.sigmoid(out)
    return out


In [10]:
# Create Dataset
features = torch.rand(10,5)

# Create Model

model = Model(features.shape[1])

# Forward Pass
model(features) # We can also do this model.forward(features)

tensor([[0.4850],
        [0.4479],
        [0.3969],
        [0.4003],
        [0.5027],
        [0.4387],
        [0.4078],
        [0.4429],
        [0.4160],
        [0.4101]], grad_fn=<SigmoidBackward0>)

In [11]:
# Show Model Weights
model.linear.weight

Parameter containing:
tensor([[-0.1044,  0.1235,  0.4292, -0.2963, -0.0353]], requires_grad=True)

In [13]:
# Show Model Bias
model.linear.bias

Parameter containing:
tensor([-0.4024], requires_grad=True)

In [14]:
# !pip install torchinfo

In [15]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00