In [34]:
import numpy as np
import torch

In [35]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [36]:
# Converting to Numpy
b = a.numpy()

In [37]:
b

array([1, 2, 3])

In [38]:
type(b)

numpy.ndarray

In [39]:
# Converting form Numpy to Torch
c = np.array([1,2,3])
c

array([1, 2, 3])

In [41]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])