In [1]:
import numpy as np

In [2]:
# Checking Version of Pytorch
import torch
print(torch.__version__)


2.6.0+cu124


In [3]:
# Checking Availability of GPU
if torch.cuda.is_available():
  print("GPU is Available")
  print(torch.cuda.get_device_name(0))
else:
  print("GPU UnAvailable. You are using CPU")

GPU UnAvailable. You are using CPU


# **Creating Tensor**

In [4]:
# Using Empty Function
torch.empty(2,3)

tensor([[2.2720e-40, 5.3369e-08, 3.0376e+35],
        [0.0000e+00, 0.0000e+00, 2.3107e-41]])

In [5]:
# Check Type of Tensors
a = torch.empty(2,3)
print(a.dtype)

torch.float32


In [6]:
# Creating Zero Tensor
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using Numpy Creating Zeros
x = np.zeros((2,3))
type(x)

numpy.ndarray

In [8]:
# Creating Ones with Torch
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
type(x)

torch.Tensor

In [10]:
# Creating Random Tensors with Torch
x = torch.rand(2,3)
x

tensor([[0.6168, 0.9174, 0.5110],
        [0.3253, 0.3542, 0.2941]])

In [11]:
type(x)

torch.Tensor

In [12]:
## Using Manual Seed to Make Data Consistent
torch.manual_seed(42)
torch.rand(2,3)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [13]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [14]:
# Creating Custom Tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# Creating Custom Tensors with Arrange Method
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [16]:
# Creating Custom Tensor with LinSpaces Method
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [17]:
# Creating Custom Tensor with Eye (Identity) Method
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
# Creating Custom Tensor with full Method
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

# **Tensor Shapes**

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
# Finding Shape of Tensor
x.shape

torch.Size([2, 3])

In [21]:
# Creating Empty Tensor of Shape X_tensor
torch.empty_like(x)

tensor([[3631421048947435063, 3180160581922730804, 4189022153932546592],
        [3471489377445749280, 4192905490737605943, 3833458513866799155]])

In [22]:
# Creating Zero Tensor of Shape X_tensor
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
# Creating One Tensor of Shape X_tensor
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
# Creating Random Tensor of Shape X_tensor
torch.rand_like(x,dtype=torch.float16)

tensor([[0.8418, 0.5098, 0.7998],
        [0.0591, 0.2275, 0.6045]], dtype=torch.float16)

# **Tensor Data Types**

In [25]:
# Finding Data Type of Tensor
x.dtype

torch.int64

In [26]:
# Assign Data Type
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float16)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [27]:
# Converting Data Type to Other Data type
x.to(dtype=torch.float16)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [28]:
x.dtype

torch.int64

In [29]:
# ReConverting Data Type of X to Int Again
x.to(torch.int16)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)

In [30]:
x.dtype

torch.int64

# **Mathmatical Operations**

**1. Scalar Operations**

In [31]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [32]:
# Addition
x + 2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [33]:
# Substraction
x - 2

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

In [34]:
# Multiplication
x * 2

tensor([[1.7388, 1.1354],
        [1.4822, 0.8588]])

In [35]:
# Division
x / 2

tensor([[0.4347, 0.2839],
        [0.3705, 0.2147]])

In [36]:
# Int Division
x // 2

tensor([[0., 0.],
        [0., 0.]])

In [37]:
# Power
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

**2. Element Wise Operation**

In [38]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [39]:
# Addition
a + b

tensor([[1.1551, 1.0153],
        [0.5635, 1.4591]])

In [40]:
# Subtraction
a - b

tensor([[ 0.6158,  0.1325],
        [-0.0303, -0.2042]])

In [41]:
# Multiplication
a * b

tensor([[0.2387, 0.2533],
        [0.0792, 0.5218]])

In [42]:
# Division
a / b

tensor([[3.2839, 1.3003],
        [0.8978, 0.7544]])

In [43]:
# Power
a**b

tensor([[0.9677, 0.7826],
        [0.6753, 0.6787]])

In [44]:
# Modulus
a % b

tensor([[0.0765, 0.1325],
        [0.2666, 0.6274]])

In [45]:
# Absolute
c = torch.tensor([1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [46]:
# Negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [47]:
# round
d = torch.tensor([1.2,3.3,4.8])
torch.round(d)

tensor([1., 3., 5.])

In [48]:
# Ceil
torch.ceil(d)

tensor([2., 4., 5.])

In [49]:
# Floor
torch.floor(d)

tensor([1., 3., 4.])

In [50]:
# Clamp : It set Limit the Min and Max Values
torch.clamp(d,min=1.5 , max=3.5)

tensor([1.5000, 3.3000, 3.5000])

**3. Reduction Operation**

In [51]:
e = torch.randint(size=(2,3),dtype=torch.float32,low=0,high=10)
e

tensor([[9., 3., 1.],
        [9., 7., 9.]])

In [52]:
## Sum : It will Summ all the Elments in that Tensor
torch.sum(e)

tensor(38.)

In [53]:
# Sum Along Columns
torch.sum(e,dim=0)

tensor([18., 10., 10.])

In [54]:
#Sum Along Rows
torch.sum(e,dim=1)

tensor([13., 25.])

In [55]:
# Mean
torch.mean(e)

tensor(6.3333)

In [56]:
# Mean Along the Column
torch.mean(e,dim=0)

tensor([9., 5., 5.])

In [57]:
# Median
torch.median(e)

tensor(7.)

In [58]:
# Min and Max
torch.min(e) , torch.max(e)

(tensor(1.), tensor(9.))

In [59]:
# Product
torch.prod(e)

tensor(15309.)

In [60]:
# Standard Deviation
torch.std(e)

tensor(3.5024)

In [61]:
# Variance
torch.var(e)

tensor(12.2667)

In [62]:
# ArgMax : Gives index of Max value
torch.argmax(e)

tensor(0)

In [63]:
# ArgMin : Gives index of Min Value
torch.argmin(e)

tensor(2)

**4. Matrix Operation**

In [64]:
f = torch.randint(size=(2,3) , low = 0 , high = 10)
g = torch.randint(size=(3,2) , low = 0 , high = 10)


In [65]:
f

tensor([[2, 0, 5],
        [9, 3, 4]])

In [66]:
g

tensor([[9, 6],
        [2, 0],
        [6, 2]])

In [67]:
# Matric Multiplication
torch.matmul(f,g)

tensor([[ 48,  22],
        [111,  62]])

In [68]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [69]:
# Transpose
torch.transpose(f,0,1)

tensor([[2, 9],
        [0, 3],
        [5, 4]])

In [70]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 9., 7.],
        [3., 3., 4.],
        [3., 7., 0.]])

In [71]:
# Determinant
torch.det(h)

tensor(-4.0000)

In [72]:
# Inverse
torch.inverse(h)

tensor([[  7.0000, -12.2500,  -3.7500],
        [ -3.0000,   5.2500,   1.7500],
        [ -3.0000,   5.5000,   1.5000]])

**5. Comparison Operation**

In [73]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 0, 9],
        [6, 9, 5]])
tensor([[4, 8, 8],
        [6, 0, 0]])


In [74]:
# Greater Then
i > j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [75]:
# Less Then
i < j

tensor([[False,  True, False],
        [False, False, False]])

In [76]:
# Equal to
i == j

tensor([[False, False, False],
        [ True, False, False]])

In [77]:
# Less Then Equal to
i <= j

tensor([[False,  True, False],
        [ True, False, False]])

In [78]:
# Greater Then Equal to
i >= j

tensor([[ True, False,  True],
        [ True,  True,  True]])

**6. Special Functions**

In [79]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 0., 1.],
        [3., 0., 1.]])

In [80]:
# Log
torch.log(k)

tensor([[  -inf,   -inf, 0.0000],
        [1.0986,   -inf, 0.0000]])

In [81]:
# Exponential
torch.exp(k)

tensor([[ 1.0000,  1.0000,  2.7183],
        [20.0855,  1.0000,  2.7183]])

In [82]:
# SQRT
torch.sqrt(k)

tensor([[0.0000, 0.0000, 1.0000],
        [1.7321, 0.0000, 1.0000]])

In [83]:
# Sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.5000, 0.7311],
        [0.9526, 0.5000, 0.7311]])

In [84]:
# SoftMax
torch.softmax(k,dim=0)

tensor([[0.0474, 0.5000, 0.5000],
        [0.9526, 0.5000, 0.5000]])

In [85]:
# Relu
z = torch.randint(size=(2,3), low=-5, high=10, dtype=torch.float32)
z
print(z)
print(torch.relu(z))

tensor([[-4., -3.,  4.],
        [-1.,  8.,  8.]])
tensor([[0., 0., 4.],
        [0., 8., 8.]])


# **Inplace Operations**

In [86]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])
tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])


In [87]:
# tensor.add_() Stores Value in old Tensor , Instead of New Tensor
m.add_(n)

tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])

In [88]:
m

tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])

In [89]:
n

tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])

In [90]:
# Relu : New Vector is Created
torch.relu(m)

tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])

In [91]:
# Value is Added to Old Vector
m.relu_()

tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])

# **Copy a Tensor**

In [92]:
a = torch.rand(2,3)
a

tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [93]:
b = a

In [94]:
a[0][0] = 0

In [95]:
a

tensor([[0.0000, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [96]:
b

tensor([[0.0000, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [97]:
id(a)

138321010516400

In [98]:
id(b)

138321010516400

In [99]:
# Cloning
b = a.clone()


In [100]:
a

tensor([[0.0000, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [101]:
b

tensor([[0.0000, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [102]:
a[0][0] = 10

In [103]:
a

tensor([[10.0000,  0.2477,  0.6524],
        [ 0.6057,  0.3725,  0.7980]])

In [104]:
b

tensor([[0.0000, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])

In [105]:
id(a)

138321010516400

In [106]:
id(b)

138316816021360