# **ReShaping Tensors**

In [16]:
a = torch.ones((4,4))
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# Reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [22]:
# Flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
# Permute
b = torch.rand(2,3,4)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [31]:
# UnSqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [33]:
# Squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])