# **Tensor Operation on GPU**

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [7]:
device = torch.device("cuda")

In [8]:
device

device(type='cuda')

In [9]:
# Creating New TEnsor on GPU
torch.rand((2,3),device=device)

tensor([[0.0799, 0.9985, 0.7504],
        [0.5543, 0.9457, 0.3307]], device='cuda:0')

In [10]:
# Moving Existing Tensor to GPU
a = torch.rand((2,3))
a

tensor([[0.0738, 0.1836, 0.7704],
        [0.0077, 0.5916, 0.9163]])

In [11]:
b = a.to(device=device)
b

tensor([[0.0738, 0.1836, 0.7704],
        [0.0077, 0.5916, 0.9163]], device='cuda:0')

In [12]:
b + 5

tensor([[5.0738, 5.1836, 5.7704],
        [5.0077, 5.5916, 5.9163]], device='cuda:0')

In [14]:
import time

# Define Size of Matrices
size = 10000

# Create Random Matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# Measure Time on CPU
strat_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - strat_time

print(f"Time on CPU : {cpu_time}")

# Move Matrixes to GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

# Measure Time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() # Ensure All GPU Operations are Complete
gpu_time = time.time() - strat_time

print(f"Time on GPU : {gpu_time}")



Time on CPU : 24.815616846084595
Time on GPU : 25.67122173309326
