In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder


In [ ]:
df = pd.read_csv("/content/data.csv")
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0           M        17.99  ...          0.4601                  0.11890
1           M        20.57  ...          0.2750                  0.08902
2           M        19.69  ...          0.3613                  0.08758
3           M        11.42  ...          0.6638                  0.17300
4           M        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564         M        21.56  ...          0.2060                  0.07115
565         M        20.13  ...          0.2572                  0.06637
566         M        16.60  ...          0.2218                  0.07820
567         M        20.60  ...          0.4087                  0.12400
568         B         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [12]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train

array([[-0.65216128, -0.41100418, -0.64051777, ..., -0.19773859,
        -0.68739579, -0.36548102],
       [-1.13452871, -0.98166556, -1.14810529, ..., -1.57908604,
         0.02554928, -0.39729998],
       [ 1.64125034,  0.44848174,  1.62374943, ...,  1.96776526,
         1.0910496 ,  0.16536537],
       ...,
       [-0.37198379, -0.38538264, -0.4275235 , ..., -1.18716034,
        -1.17783932, -1.28398845],
       [ 0.65340806,  0.32270332,  0.65711531, ...,  0.67608796,
         0.29192436, -0.130551  ],
       [ 4.0733065 , -0.19904423,  4.07171895, ...,  0.694388  ,
        -1.98793294, -1.54914649]])

In [14]:
X_test

array([[ 1.02023838e+00, -1.05967173e-03,  1.00024950e+00, ...,
         1.21898893e+00,  1.77147177e-02, -3.07146247e-01],
       [-2.91107808e-01,  1.35222304e+00, -3.59315114e-01, ...,
        -8.35037219e-01, -9.56904692e-01, -1.14292437e+00],
       [-1.84235982e-01, -6.83524101e-01, -2.13273855e-01, ...,
        -3.68843891e-01, -1.36116805e+00, -4.33891788e-01],
       ...,
       [ 9.04701273e-01, -6.81194871e-01,  1.03791057e+00, ...,
         2.15076558e+00,  1.80086084e+00,  1.13690441e+00],
       [ 2.62331577e+00,  1.17731065e-01,  2.54853791e+00, ...,
         1.71461481e+00, -1.36235270e-02, -6.20032729e-01],
       [-8.57239644e-01, -1.02359170e+00, -8.58951970e-01, ...,
        -7.08004493e-01,  4.47048670e-01, -6.14729568e-01]])

In [15]:
#Label Encoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,

In [17]:
y_test

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0])

In [18]:
# Converting from numpy to Tensor
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [22]:
X_train[0]

tensor([-0.6522, -0.4110, -0.6405, -0.6368,  0.7360, -0.1537, -0.4553, -0.1095,
        -0.7880,  0.5078,  0.1483,  1.1925,  0.1659, -0.1827, -0.1687, -0.4180,
        -0.4733,  0.2041, -0.2926, -0.5638, -0.5533,  0.3601, -0.5369, -0.5595,
         0.0847, -0.4457, -0.6513, -0.1977, -0.6874, -0.3655],
       dtype=torch.float64)

In [23]:
X_train.shape

torch.Size([455, 30])

In [24]:
y_train.shape

torch.Size([455])

# **Defining the Model**

In [28]:
class MySimpleNN():

  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)


  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self,y_pred,y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss




tensor([0.], dtype=torch.float64, requires_grad=True)


In [ ]:
learning_rate = 0.1
epochs = 25

# **Training Pipeline**

In [ ]:
# create model
model = MySimpleNN(X_train)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train)

  # loss calculate
  loss = model.loss_function(y_pred, y_train)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')